version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/:ro

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    ports:
#      - 8081:8081
#    restart: always
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_URL=mongodb://rootuser:rootpass@mongodb/?authSource=admin&authMechanism=SCRAM-SHA-1
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#    depends_on:
#      - mongodb

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'springapp'
    container_name: springapp
    restart: always
    environment:
      - PORT=8000
    ports:
      - 8080:8080
    depends_on:
      - mongodb
#      - mongo-express

# volumes:
#    data: {}