version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mongosh --eval "db.adminCommand(\"ping\")" mongodb://%s:%s@mongodb/?authSource=project_db&authMechanism=SCRAM-SHA-1'
        ]
      interval: 0s
      timeout: 3s
      retries: 5
      start_period: 1s
      start_interval: 1s

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'springapp'
    container_name: springapp
    restart: always
    environment:
      - PORT=8000
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_healthy